/*
 * generated by Xtext 2.17.0
 */
package unice.xtext.pfe.legalsc


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LegalSCRuntimeModule extends AbstractLegalSCRuntimeModule {
}
