/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
