grammar org.xtext.example.testdsl.TestDsl with org.eclipse.xtext.common.Terminals

generate testDsl "http://www.xtext.org/example/testdsl/TestDsl"

Domainmodel :
    (elements+=Type)*;
  
Type:
    DataType | Entity;
  
DataType:
    'datatype' name=ID;
 
Entity:
    'entity' name=ID ('extends' superType=[Entity])? '{'
        (features+=Feature)*
    '}';
 
Feature:
    (many?='many')? name=ID ':' type=[Type];
